version: '3.8'

services:
  tauro-container:
    image: tauro:latest
    container_name: tauro-container
    ports:
      - "8888:8888"  # Jupyter
      - "8080:8080"  # General web apps
      - "4040:4040"  # Spark UI
      - "8000:8000"  # API (nuevo puerto)
    volumes:
      - .:/tauro
    environment:
      - API_PORT=8000
      - PYTHONUNBUFFERED=1
    working_dir: /tauro
    tty: true
    stdin_open: true
    networks:
      - tauro-network
    deploy:
      resources:
        limits:
          cpus: '1'        # Limita el uso a 0.5 nucleos de CPU (la mitad de un nucleo)
          memory: 512M        # Limita la memoria a 512 Megabytes
        reservations:
          cpus: '0.5'       # Reserva 0.5 nucleos de CPU
          memory: 512M       # Reserva 512 Megabytes de memoria

networks:
  tauro-network:
    driver: bridge